# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('uuid', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('edit_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('abn_number', models.CharField(max_length=40)),
                ('is_individual', models.CharField(max_length=40)),
                ('address_street', models.CharField(max_length=60)),
                ('address_city', models.CharField(max_length=60)),
                ('address_state', models.CharField(max_length=25)),
                ('address_postcode', models.CharField(max_length=10)),
                ('address_country', models.CharField(max_length=25)),
                ('fax_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=60)),
                ('billing_address', models.CharField(max_length=250)),
                ('badges', models.CharField(max_length=250)),
                ('tax_rate_uuid', models.CharField(max_length=38)),
                ('parent_company_uuid', models.CharField(default='', max_length=38)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Contact',
            fields=[
                ('uuid', models.CharField(max_length=38, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('edit_date', models.DateTimeField()),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=16)),
                ('mobile', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('contact_type', models.CharField(max_length=60)),
                ('is_primary_contact', models.CharField(max_length=38)),
                ('company_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.Company')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNumber', models.IntegerField()),
                ('item_M8UUID', models.CharField(max_length=36)),
                ('qty', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('multiplier', models.FloatField(default=1.522)),
                ('price', models.IntegerField()),
                ('hideOnPrint', models.BooleanField(default=False)),
                ('hidePriceOnPrint', models.BooleanField(default=False)),
                ('isOption', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='M8_Item_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M8UUID', models.CharField(max_length=38)),
                ('costprice', models.IntegerField()),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('sellprice', models.IntegerField()),
                ('vendor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateIssued', models.DateField(auto_now_add=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('m8_CustomerUUID', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=60)),
                ('related_M8UUID', models.CharField(max_length=38)),
                ('total', models.IntegerField()),
                ('note', models.TextField()),
                ('private_Note', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quote.LineItem')),
                ('vendor_part_number', models.CharField(max_length=30)),
                ('purcasePrice', models.IntegerField()),
                ('associatedQuote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.Quote')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.PO')),
            ],
            bases=('quote.lineitem',),
        ),
        migrations.CreateModel(
            name='Quoteline',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quote.LineItem')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.Quote')),
            ],
            bases=('quote.lineitem',),
        ),
    ]
