# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='quote',
            name='m8_CustomerUUID',
            field=models.CharField(editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='private_Note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='related_M8UUID',
            field=models.CharField(editable=False, max_length=38),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
