# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20170123_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteline',
            name='lineitem_ptr',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='poline',
            name='po',
        ),
        migrations.AddField(
            model_name='po',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.POLine'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.LineItem'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.522, max_digits=3),
        ),
        migrations.DeleteModel(
            name='Quoteline',
        ),
    ]
