# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20170123_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='abn_number',
            field=models.CharField(editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_city',
            field=models.CharField(default='Brockville', max_length=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_country',
            field=models.CharField(default='Canada', max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_state',
            field=models.CharField(default='Ont', max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='badges',
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='billing_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_individual',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent_company_uuid',
            field=models.CharField(editable=False, max_length=38),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_rate_uuid',
            field=models.CharField(blank=True, editable=False, max_length=38),
        ),
        migrations.AlterField(
            model_name='company',
            name='uuid',
            field=models.CharField(editable=False, max_length=38, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poline',
            name='purcasePrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
