# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20170124_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='lines',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.LineItem'),
        ),
    ]
