# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20170124_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isVendor',
            field=models.BooleanField(default=False),
        ),
    ]
