# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20170125_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quote.Company'),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='contact_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='first',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='last',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='company_contact',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item_M8UUID',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='m8_item_detail',
            name='costprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='m8_item_detail',
            name='sellprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='m8_item_detail',
            name='vendor',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
