# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_auto_20170125_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quote.Quote'),
        ),
    ]
