# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_lineitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
