# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_auto_20170127_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M8UUID', models.CharField(max_length=38)),
                ('item_code', models.CharField(blank=True, max_length=65)),
                ('description', models.CharField(default='', max_length=120)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('lastModified', models.DateTimeField(auto_now=True)),
                ('sells_for', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('vendor', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='M8_Item_Detail',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='parent_company_uuid',
            new_name='m8_parent_uuid',
        ),
        migrations.RenameField(
            model_name='lineitem',
            old_name='price',
            new_name='sell_price',
        ),
        migrations.RenameField(
            model_name='poline',
            old_name='associatedQuote',
            new_name='associated_quote',
        ),
        migrations.RenameField(
            model_name='poline',
            old_name='purcasePrice',
            new_name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='item_M8UUID',
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quote.Company'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='note',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='po',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('REC', 'Received'), ('BO', 'Backorder')], default='Draft', max_length=15),
        ),
        migrations.AddField(
            model_name='poline',
            name='purchase_notes',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='poline',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('ORDER', 'Received'), ('BO', 'Backorder')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='poline',
            name='vendor_part_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quote.Item'),
        ),
    ]
