# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_auto_20170127_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='badges',
            field=models.CharField(blank=True, editable=False, max_length=99),
        ),
        migrations.AlterField(
            model_name='company',
            name='billing_address',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quote.Company'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('ORDER', 'Order')], default='', max_length=15),
        ),
    ]
