# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0015_auto_20170128_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='M8UUID',
            field=models.CharField(blank=True, max_length=38),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
